# Site settings
title: isonomia
email: "contact[@]isonomia.fr"
description: "Photo Journal"
url: "https://isonomya.github.io"
baseurl: "/isonomya"
facebook_username: "isonomiapure"
twitter_username: "isonomia_pure"
instagram_username: "isonomia_pure"
share: true

# Owner/author information
owner:
  name:   isonomia
  avatar: avatar.png
  favicon: favicon.ico
  info: Decolonial Antiraciste Feministe 

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://isonomya.github.io/isonomya/gallery/"
  - JOURNAL: "https://isonomya.github.io/isonomya/journal/"
  - ABOUT: "https://isonomya.github.io/isonomya/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
# permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
